### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by janacm** [jersey/jersey#3547]
In the docs for the Client API (https://jersey.java.net/documentation/latest/client.html#client.ex.formpost) I found the following errors.

1) Section **5.3.5. Invoking a HTTP request**, suggests that 
`response.readEntity(String.class)` will return a type of String, but in reality it returns a generic `T`, it can be casted to a String, but that is not the intended purpose of this method. 

2) Typo in same section 

> that since ve have 

Should be "we" not "ve"

**Comment by pavelbucek** [comment]
ad 1) .. when `response.readEntity(String.class)` is invoked, the return type is really String, not "T".

**Comment by pavelbucek** [comment]
2) is fixed in the master branch.
