### ISSUE TITLE
java.net has been shut down

### ISSUE THREAD

**Issue by marco-ceriani** [jersey/jersey#3554]
Oracle has shut down jersey.java.net. Is there a plan to put the documentation back online?

**Comment by pavelbucek** [comment]
yes, definitely.

we are already working on that, please be patient. Also, please keep this for code/doc related issues and use groups.io for general discussion - https://javaee.groups.io/g/jersey

Regards,
Pavel

**Comment by pavelbucek** [comment]
new webpage will be https://jersey.github.io/ (some content is already pushed, but it is still work in progress - there might be dead links, outdated info, etc.)
