### ISSUE TITLE
Fix broken documentation links on jersey.github.io

### ISSUE THREAD

**Issue by mrstewar** [jersey/jersey#3555]
Looks like your standard build of the documentation is still referencing jersey.java.net so all the links in the docs are broken (at least for me, I can't reach the jersey.java.net site any longer).

**Comment by mrstewar** [comment]
Example of what I'm talking about:
https://jersey.github.io/documentation/latest/security.html, first line of 16.1.1. SecurityContext there is a link for SecurityContext that points at https://jersey.java.net/apidocs-javax.jax-rs/2.0.1/javax/ws/rs/core/SecurityContext.html
rather than the correct https://jersey.github.io/apidocs-javax.jax-rs/2.0.1/javax/ws/rs/core/SecurityContext.html

**Comment by mrstewar** [comment]
Gahh, bad example as jaxrs is not your repo although that's broken too.  Here is a better example

Actual: https://jersey.java.net/apidocs/2.23/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html

Should be:
https://jersey.github.io/apidocs/2.23/jersey/org/glassfish/jersey/server/filter/RolesAllowedDynamicFeature.html

**Comment by mrstewar** [comment]
Obvious workaround is to manually update the links after clicking on them and getting 404s, but that's tedious

**Comment by gauravsak** [comment]
How about redirecting jersey.java.net to jersey.github.io? Who could do that?

**Comment by cen1** [comment]
Not to mention all documentation links found through google are now broken. Java.net just offers a generic error page with no redirect or mention where to find the new documentation. This was a very poor transition of docs.

**Comment by pavelbucek** [comment]
we cannot do much about java.net redirect. I believe there is a plan to do that, but that's not something we can influence.

ad broken links - Jersey 2.26-b04 was released recently, so /latest/ everywhere should work. Let me do another scan for jersey.java.net links..

**Comment by pavelbucek** [comment]
done. please let us know if you find any forgotten reference.

**Comment by schlosna** [comment]
The release notes for 2.26-b04 appear to be missing, as https://jersey.github.io/release-notes/index.html redirects to https://jersey.github.io/release-notes/2.26-b04.html which returns `HTTP 404` and there does not appear to be any `2.26-b04.html` in https://github.com/jersey/jersey.github.io/blob/master/release-notes/

**Comment by pavelbucek** [comment]
True. We did have integration with Java.net JIRA and we didn't update it to work with github yet..
