### ISSUE TITLE
Injection problem when using named Suppliers that provide the same type in Jersey 2.26-SNAPSHOT.

### ISSUE THREAD

**Issue by cfiehe** [jersey/jersey#3556]
I am using Jersey 2.26-SNAPSHOT and I am currently facing the following issue: There is a bug, when you use named Suppliers that provide the same type. It seems to me that the named qualifier is not considered. Have a look to the following example:

	public class TestResource {

		@Inject @Named("OtherTest")
		public String x;

	}

	public class TestSupplier implements Supplier<String> {

		@Override
		public String get() {
			return "Test";
		}

	}

	public class OtherTestSupplier implements Supplier<String> {

		@Override
		public String get() {
			return "OtherTest";
		}

	}

	...
	resourceConfig.register(new AbstractBinder() {
		@Override
		protected void configure() {
			bindFactory(TestSupplier.class).named("Test").to(String.class).in(RequestScoped.class);
			bindFactory(OtherTestSupplier.class).named("OtherTest").to(String.class).in(RequestScoped.class);
		}
	}
	...

In this exampe the value `"Test"` is injected into `TestResource`. That is not right. May someone please have a look.

**Comment by cfiehe** [comment]
I have created a pull request that fixes the problem:
https://github.com/jersey/jersey/pull/3557

**Comment by pavelbucek** [comment]
fixed in the master branch.
