### ISSUE TITLE
Except Maven，where can i download all jar from（the latest version）？ 

### ISSUE THREAD

**Issue by pangguoming** [jersey/jersey#3575]
i am doing a restful project with tomcat 7,  where can i download all jar from?  i need add that jar files to my project build path.

**Comment by pavelbucek** [comment]
From Maven. We don't have anything else.

It's not that hard, you can look into [dependency:copy-dependencies](https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html) plugin or dependency:get.

Jersey also publishes [RI bundle](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.glassfish.jersey.bundles%22%20AND%20a%3A%22jaxrs-ri%22), but that doesn't contain everything from Jersey. It corresponds to what is defined in JAX-RS. (meaning you'll need to download some jars for other features if you need to use them).

Also, see [jersey.github.io/download](https://jersey.github.io/download.html).

**Comment by pangguoming** [comment]
i did it ,thanks
