### ISSUE TITLE
Broken links in User Guide

### ISSUE THREAD

**Issue by nitishch** [jersey/jersey#3578]
After the move to Github, many of the API links in [user guide](https://jersey.github.io/documentation/latest/jaxrs-resources.html) are broken.

Examples:
@Path: https://jersey.github.io/apidocs-javax.jax-rs/2.1-m07/javax/ws/rs/Path.html
@Put: https://jersey.github.io/apidocs-javax.jax-rs/2.1-m07/javax/ws/rs/PUT.html

**Comment by pavelbucek** [comment]
this is not related to move to github, it would be broken on java.net as well.

this is related to the state of the JAX-RS api; javadocs are available on https://jax-rs.github.io/apidocs/2.1. Will be fixed when JAX-RS 2.1 is released..
