### ISSUE TITLE
Why java Bean get a more "key-value" json for  title case of an arges?

### ISSUE THREAD

**Issue by Abvatous** [jersey/jersey#3589]
HI~
This is my java bean:
public class User {

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public int age;
    public String sex;
    public String Name;

}`

As we can see   "public String Name;" ,the "N" is the title case.
It made me get more k-v-json:
`{
    "age": 25,
    "sex": "Man",
    "Name": "ab",
    "name": "ab"
}`

If I use the "name",I got the right one:
`{
    "age": 25,
    "sex": "Man",
    "name": "ab"
}
`

**Comment by pavelbucek** [comment]
you need to state which json provider are you using.

**Comment by sezginruhi** [comment]
try @XmlElement(name = "Name")
`
@XmlRootElement(name = "User")
@XmlAccessorType(XmlAccessType.FIELD)
public class User {

	@XmlElement(name = "age")
	public int age;
	@XmlElement(name = "sex")
	public String sex;
	@XmlElement(name = "Name")
	public String Name;
	/**
	 * @return the age
	 */
	public final int getAge() {
		return age;
	}
	/**
	 * @param age the age to set
	 */
	public final void setAge(int age) {
		this.age = age;
	}
	/**
	 * @return the sex
	 */
	public final String getSex() {
		return sex;
	}
	/**
	 * @param sex the sex to set
	 */
	public final void setSex(String sex) {
		this.sex = sex;
	}
	/**
	 * @return the name
	 */
	public final String getName() {
		return Name;
	}
	/**
	 * @param name the name to set
	 */
	public final void setName(String name) {
		Name = name;
	}
	
	
}`

**Comment by Abvatous** [comment]
Maybe I get somrthing wrong~

**Comment by Abvatous** [comment]
Maybe I got something worng~
Sorry ~ 
The dependence of json I used is " compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.26-b03'".
Thanks for yours help~~

**Comment by Abvatous** [comment]
@pavelbucek 
The dependency of json I used:
     compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.26-b03'.
@sezginruhi THX

**Comment by Abvatous** [comment]
@pavelbucek @sezginruhi THX！！
