### ISSUE TITLE
SseEventSink invokes custom WriterInterceptor with wrong type, then throws NPE

### ISSUE THREAD

**Issue by mkarg** [jersey/jersey#3592]
Given this code...
```
sseEventSink.send(sse.newEventBuilder().mediaType(MediaType.APPLICATION_XML_TYPE).data(new GenericType<Optional<SensorValue>>() {}, readSensor()).build());
```
...where `readSensor()` actually returns an instance of `Optional<SensorValue>` and where `SensorValue` is a `@XmlRootElement`.

When invoked within a SSE connection initiation resource method, it will invoke a hypothetical custom WriterInterceptor with the **wrong type and generic type** in the interceptor context. While the *expected* type and generic type is `Optional` and `Optional<SensorValue>`, *actually* the interceptor context has the type and generic type both set to `JerseyEventSink`!

When the custom WriterInterceptor then invokes `context.proceed()` a NPE is thrown:

```
Jun 23, 2017 11:30:28 PM org.glassfish.grizzly.ProcessorExecutor execute
WARNUNG: GRIZZLY0029: Error during Processor execution. Connection=null ioEvent=NONE processor=null
java.lang.NullPointerException
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.filterchain.FilterChainContext$1.run(FilterChainContext.java:202)
        at org.glassfish.grizzly.filterchain.FilterChainContext.resume(FilterChainContext.java:226)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:242)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
```

*A complete sample project can be provided if needed, just let me know. :-)*

**Comment by mkarg** [comment]
I assume that one of two problems being the actual cause (possibly both of them):
(1) I provided the wrong generic type. Actually the data is `Optional<SensorValue>` but the MBW is for `SensorValue`. The transformation from the optional is intended to be performed by the custom `WriterInterceptor`. But when providing only `SensorValue` as the generic type, a different crash happens inside of Jersey.
(2) Apparently inside Jersey the exact same code is executed for SSE and for chunked encoding. Unfortunately there is a difference: Chunked encoding gets intercepted once, then chunked. SSE must not get intercepted first, but must get intercept each chunk. This might explain why the interceptor is invoked with the wrong class.

**Comment by pavelbucek** [comment]
Where do you see that (2) must happen?

Actually, I'm pretty sure that spec says that only MBW gets invoked per each event and that's it, interceptors are invoked only once per EventSink processing, which is what you see.

**Comment by pavelbucek** [comment]
Please see this: https://github.com/jax-rs/spec/commit/b4b0d91fc902d58dfa1670b2ee1bc34a640bb6f5

**Comment by mkarg** [comment]
Closing as invalid. Sad but true, this apparently works according to the current draft of the JAX-RS 2.1 specification.
