### ISSUE TITLE
Incorrect Reference in UG Chapter 3

### ISSUE THREAD

**Issue by sjdavies** [jersey/jersey#3595]
Hi All,
was just reading through the 2.26-b06 User Guide, section 3.6.

It references the JAX-RS specification, chapter 5 for details on @Context. Chapter 5 of the JAX-RS specification 2.0 is "Client API".

Should this really be a reference to Chapter 9, "Context"?

Regards,
Stephen

**Comment by pavelbucek** [comment]
It's Chapter 9 in JAX-RS 2.0, Chapter 10 in 2.1 .. let me get rid of that reference, or to refer only by name, not by number.

Thanks,
Pavel
