### ISSUE TITLE
Update license information in project.pom

### ISSUE THREAD

**Issue by sabgit** [jersey/jersey#3604]
Project license information in the pom is different than the one on the license web page https://jersey.github.io/license.html which mentions CDDL1.1 + GPLv2 w/CPE

The one in the pom has following:
maven/repository/org/glassfish/jersey/project/2.25] > cat project-2.25.pom
```
...
    <licenses>
        <license>
            <name>CDDL+GPL License</name>
            <url>http://glassfish.java.net/public/CDDL+GPL_1_1.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
...
```

**Comment by pavelbucek** [comment]
these are same licenses - if you'd open the html file, its cddl 1.1 + gpl v2.

**Comment by sabgit** [comment]
According to https://spdx.org/licenses:

- there is CDDL-1.0 and CDDL-1.1 
- there is GPL-1.0 and GPL-2.0 and GPL-2.0 w/CPE

So 'CDDL+GPL License' does not seem to automatically mean CDDL1.1 + GPLv2 w/CPE

The license reporting tools/plugins that extract license information for reporting purposes usually relies on the <license><name> defined in the POM and they are not sophisticated enough to parse what is written in the url link. (the url link btw redirects to https://javaee.github.io/glassfish/ in my browser and does not have license information either, so that probably needs to be updated as well)

Could you please update the POM to reflect the actual license names intended?

**Comment by pavelbucek** [comment]
Ah. Ok, the link is not correct, I already fixed it for JAX-RS (https://github.com/jax-rs/api/commit/3d87bab873e339c52493923381651449db91d932) and I thought I did it for Jersey as well.. will be fixed today.

**Comment by sabgit** [comment]
Could you please update the POM to reflect the actual license names intended in `<license><name>` section?

**Comment by pavelbucek** [comment]
The name seems to be ok in the referenced commit:

    <licenses>
        <license>
            <name>CDDL 1.1</name>
            <url>https://oss.oracle.com/licenses/CDDL+GPL-1.1</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>GPL2 w/ CPE</name>
            <url>https://oss.oracle.com/licenses/CDDL+GPL-1.1</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

**Comment by sabgit** [comment]
looks perfect, thanks a lot!
