### ISSUE TITLE
post a JSON

### ISSUE THREAD

**Issue by vladern** [jersey/jersey#3608]
Hi , can't get information abaut how can I pos a JSON I try with this code : Response respuesta = servicio.request("application/json").post(Entity.json(obj.toString())); , but it is not working :( . What is the correct form too post a JSON ? Becaus in your documentation I only get how to post a Form , what is pointless to my aplication.
Thank you.

**Comment by AdamLindenthal** [comment]
Hi vladern,

the call to `Entity.json()` only sets the mediaType to `application/json`, while you are still sending your object's `toString()` output, whatever it actually is (which is not apparent from your question).

To send JSON from Jersey client, you could either 
- convert your object to JSON string representation directly (manually) - using some library directly used in your code
- or (more comfortable option) "register" some JSON provider into the client (either calling `register()` when creating the client or, in some cases just putting the appropriate jersey module on the classpath) and then simply sending the entity/object, not the string: `post(Entity.json(obj))`, not ~~`post(Entity.json(obj.toString()))`~~.

If you are using Jersey on the server side as well, you would do the same (put the json provider on classpath and eventually register it) and then receive the same object (not a string) as a parameter (you should also declare, that the resorce method is expecting json using `@Consumes("application/json")` annotation.

Your question is not really detailed and the answer is rather complex, so I'd recommend you the [relevant Jersey doc section](https://jersey.github.io/documentation/latest/user-guide.html#json) and eventually checking Jersey [examples](https://github.com/jersey/jersey/tree/master/examples) - the JSON related ones. I cannot help you more, as the JSON provider choice depends on your environment and your needs.

Hope this helps a bit.

Anyway, as this is not an issue, I am closing it.
Next time, please use our [mailing list](https://jersey.github.io/mailing.html) or try e.g. StackOverflow.

Regards,
Adam
