### ISSUE TITLE
JettyConnector sends 2 User-Agent headers

### ISSUE THREAD

**Issue by hypnoce** [jersey/jersey#3609]
Hi all,

in [JettyConnector.java](https://github.com/jersey/jersey/blob/311cc47e7d83f86b925cf60700075753dbdb5387/connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java#L245) line 245, the jetty request is created with 2 headers by default : 

<img width="774" alt="screen shot 2017-07-06 at 19 05 40" src="https://user-images.githubusercontent.com/4430896/27923283-26135f70-627e-11e7-8dda-a7467f47636f.png">

The jersey ClientRequest also contains a User-Agent : 

<img width="895" alt="screen shot 2017-07-06 at 19 07 21" src="https://user-images.githubusercontent.com/4430896/27923352-6669ed46-627e-11e7-82e0-e482bd35ab42.png">

in [JettyConnector.java](https://github.com/jersey/jersey/blob/311cc47e7d83f86b925cf60700075753dbdb5387/connectors/jetty-connector/src/main/java/org/glassfish/jersey/jetty/connector/JettyConnector.java#L317) line 317, the headers are merged, resulting in :

<img width="937" alt="screen shot 2017-07-06 at 19 09 42" src="https://user-images.githubusercontent.com/4430896/27923463-b92e481a-627e-11e7-87b0-cb46709d3378.png">

Microsoft IIS 10 does not accept this and returns a 400.

**Comment by AdamLindenthal** [comment]
Done. Thanks for reporting, closing the issue.
