### ISSUE TITLE
"Invalid constant type 18" caused by javassist 3.18.1-GA

### ISSUE THREAD

**Issue by zjedi** [jersey/jersey#3618]
javassist library 3.18.1-GA that is transitively brought by jersey-client and jersey-core causes deployment-time error when used with JDK 8

> java.io.IOException: Invalid constant type 18

Manually replacing the dependency with **version 3.18.2-GA fixes the problem**. Please upgrade the dependency. Similar problem has been documented here https://stackoverflow.com/questions/30313255/reflections-java-8-invalid-constant-type

**Comment by pavelbucek** [comment]
already updated in master branch.
