### ISSUE TITLE
Missing release notes for 2.26-b08, 2.26-b07, etc.

### ISSUE THREAD

**Issue by larrywest** [jersey/jersey#3626]
The "Release Notes" link on the [main page](https://jersey.github.io) is listed as:

* `https://jersey.github.io/release-notes/index.html`

which redirects to

* `https://jersey.github.io/release-notes/2.26-b08.html`

which doesn't exist (404).  Nor does 2.26-b07.html nor 2.26-b06.html.

However, the [release notes for 2.25.1](https://jersey.github.io/release-notes/2.25.1.html) do exist at the expected location:

* `https://jersey.github.io/release-notes/2.25.1.html`

**Comment by pavelbucek** [comment]
#3581
