### ISSUE TITLE
2.26-b09 - Where did AbstractContainerRequestValueFactory go?

### ISSUE THREAD

**Issue by j1913375** [jersey/jersey#3630]
I am evaluating a migration from 2.25 to 2.26-b09, but it seems that the class AbstractContainerRequestValueFactory is no longer present.

Where did it go? Was it removed on purpose, and if so, what is the new way to inject?

Thanks.

**Comment by pavelbucek** [comment]
new way to inject what?

(for the record: that class was in internal.* package, so technically you were not supposed to use that anyway).

(please use mailing list for questions, this should be reserved for issues; see https://javaee.groups.io/g/jersey)
