### ISSUE TITLE
Invalid use of builder pattern in ApacheConnector

### ISSUE THREAD

**Issue by harschware** [jersey/jersey#3634]
While attempting to work around an issue where I wanted to set requestConfigBuilder.setCookieSpec(CookieSpecs.STANDARD) in ApacheConnector (unfortunately I had to copy the entire class source so I could modify the constructor), I noticed an incorrect usage of the builder pattern at these locations.

https://github.com/jersey/jersey/blob/master/connectors/apache-connector/src/main/java/org/glassfish/jersey/apache/connector/ApacheConnector.java#L290

https://github.com/jersey/jersey/blob/master/connectors/apache-connector/src/main/java/org/glassfish/jersey/apache/connector/ApacheConnector.java#L295

It should be a really quick fix.

(And if someone were so inclined a new base method in there to allow a derived class to get in to the builder chain would be nice)

**Comment by pavelbucek** [comment]
I don't see any "incorrect" use, see setCookieSpec implementation:

```
        public Builder setCookieSpec(final String cookieSpec) {
            this.cookieSpec = cookieSpec;
            return this;
        }
``` 

user of that api can choose whether the method will be invoked as it is currently done in the code or if it will be chained in a "fluent" pattern invocation. Nothing wrong with doing it as it is done in ApacheConnector right now.

**Comment by harschware** [comment]
Ah yes, my mistake.  Thanks for clarifying.  Any pointers on how to setCookieSpec via ApacheConnector without having to copy the source and factor a new class?
