### ISSUE TITLE
Adding a Resource to ResourceConfig at runtime

### ISSUE THREAD

**Issue by mohsenebrahimy** [jersey/jersey#3639]
I have created a new resource at rumtime using org.glassfish.jersey.server.model.Resource class, but this is not possible to add this new Resource to the ResourceConfig, because it is solely possible to register resources when ResourceConfig is being created.
My question is that why Jersey prevents me to register a resource after the ResourceConfig creation.

**Comment by pavelbucek** [comment]
Jersey has to scan all resources prior to serving first request, see package o.g.j.server.model (in core-server module). Adding resource on the fly would need significant refactoring and sometimes isn't really possible - it could conflict with existing ones, then you need to be able to handle those issues .. etc.

We already do have a mechanism which allows an app to be reloaded - that could achieve what you need, see https://github.com/jersey/jersey/tree/master/examples/reload.

Please use mailing list (https://javaee.groups.io/g/jersey) for questions like that, issue tracker should be used for issues.
