### ISSUE TITLE
Repackaged maven dependencies seem to be missing in 2.26

### ISSUE THREAD

**Issue by dreis2211** [jersey/jersey#3671]
Hey,

is it intended that the `repackaged` maven dependencies seem to be missing in 2.26?

E.g. `jersey-guava` seems to have stopped after b03:
https://mvnrepository.com/artifact/org.glassfish.jersey.bundles.repackaged/jersey-guava

Am I missing something?

Cheers,
Christoph

**Comment by fabriziocucci** [comment]
I may be wrong but I think that was done on purpose. 

Have a look at the following chronologically ordered commits:
1. [Moving to Java 8 and minimizing Guava usage](https://github.com/jersey/jersey/commit/87913454fb888865166115b5aa5e096c45e00616)
2. [Extracting (minimal?) set of Guava classes to core-common](https://github.com/jersey/jersey/commit/ac34707df4ca97028ce6abfc2eeb4a39eae77b81)
3. [Repackaging Guava](https://github.com/jersey/jersey/commit/e5eb133193fa091b841f41ee5d1eab5611e45ec9)

**Comment by pavelbucek** [comment]
Fabricio is true, that has been done on purpose.

@dreis2211, what is the actual issue here? (closing, feel free to add comments, the issue can be reopened).
