### ISSUE TITLE
Unable to load the resource created using maven

### ISSUE THREAD

**Issue by MurthyMajeti** [jersey/jersey#3729]
Hello,

I am new to Rest and Jersey as well. I have created a maven project using the web-app archetypes of version 2.6. The project is successfully created. When I try to run this project against a tomcat server, I am facing issues in loading the default MyResource.java class using web browser. It says 404 resource not found. I haven't touched anything on the project.

Why am I getting the 404 - Resource not found for the maven created jersey project??

Can somebody help me out..??

**Comment by jansupol** [comment]
Hi Murthy, I am sorry, this is a tracker of bugs in Jersey. You would need to check some other forum with question like this. Have you tried [stackoverflow](https://stackoverflow.com)?
