### ISSUE TITLE
Issue with Rest GET Request 

### ISSUE THREAD

**Issue by krunalramanuj** [jersey/jersey#3762]
I have included following dependency in pom.xml file.

---------------------------------------------------------------
 <dependency>
                        <groupId>com.sun.jersey</groupId>
                        <artifactId>jersey-client</artifactId>
                        <version>1.19.3</version>
                </dependency>
                <dependency>
                        <groupId>com.sun.jersey</groupId>
                        <artifactId>jersey-json</artifactId>
                        <version>1.19.3</version>
                </dependency>
                <dependency>
                        <groupId>com.sun.jersey.contribs</groupId>
                        <artifactId>jersey-multipart</artifactId>
                        <version>1.19</version>
                </dependency>
----------------------------------------------------------------------

Using following code for get request:
Client is type of jersey api client
    Client client = Client.create(cfg);
     WebResource webResource = client.resource(My_URL);
     Builder responseBuilder = webResource.accept("application/json");
ClientResponse response =   responseBuilder.get(ClientResponse.class);
response.getEntity(type);   // Here type is project type.

The program is terminated with following Exception.:

in thread "main" com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class to.rtc.rtc2jira.exporter.jira.entities.Project, and Java type class to.rtc.rtc2jira.exporter.jira.entities.Project, and MIME media type text/html; charset=UTF-8 was not found

**Comment by jansupol** [comment]
Sorry, this is issue tracker for Jersey 2. For similar questions, please use different web sites, such as Stack Exchange Network. Do not forget to add ClientResponse class to the description.
