### ISSUE TITLE
Jersey BOM is broken

### ISSUE THREAD

**Issue by vpavic** [jersey/jersey#3773]
Jersey BOM provides dependency management for `org.glassfish.jersey.bundles.repackaged:jersey-jsr166e` however for the current `2.26` release this artifact is not available in Maven Central.

**Comment by joschi** [comment]
Any chance to fix this in a patch release?

**Comment by vpavic** [comment]
If the `2.26` release of [`org.glassfish.jersey.bundles.repackaged:jersey-jsr166e`](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.glassfish.jersey.bundles.repackaged%22%20AND%20a%3A%22jersey-jsr166e%22) would find its way to Maven Central that would effectively resolve the issue.

**Comment by 1605200517** [comment]
@vpavic  is this one not what you look for?
http://repo1.maven.org/maven2/org/glassfish/jersey/bundles/repackaged/jersey-jsr166e/2.26-b02/

**Comment by vpavic** [comment]
@1605200517 No, because the [BOM in subject](https://search.maven.org/remotecontent?filepath=org/glassfish/jersey/jersey-bom/2.26/jersey-bom-2.26.pom) is version `2.26`.

**Comment by 1605200517** [comment]
@vpavic  I have to excuse myself for possible misunderstanding of the procedure protocols here, but the sentence above "if the release... would find its way.." sounds somewhat obscure.
So, who could do what to help the release finding its way?

**Comment by joschi** [comment]
@1605200517 The maintainers have to create a release artifact in the correct version and upload it to Maven Central.

**Comment by jansupol** [comment]
The change has been done on 2017-02-17, the jsr 166 bits were put to core-common, and the BOM pom was not updated. That's before 2.26-b03 release. We should remove the record from BOM pom.

**Comment by vpavic** [comment]
Thanks for the update @jansupol. Do you by any chance have an approximate target date for the next release?

**Comment by jansupol** [comment]
The change is submitted, the release is scheduled right after Easter.
