### ISSUE TITLE
Handle com.fasterxml.jackson.databind.exc.InvalidFormatException inside a RequestContext

### ISSUE THREAD

**Issue by franktominc** [jersey/jersey#3787]
I'm using jackson as the json provider for jersey and I'm having some trouble. Picture the following scenario:

 - An entity have a property defined by an Enum
 - Someone sends a request with an invalid value for the Enum

Jersey will try to deserialize the request using jackson and will fail returning a 500 HTTP response. I wish to change that to a 422, since it's a client error. Where in jersey request handling could I handle this failure?

**Comment by chkal** [comment]
Did you try to define an ExceptionMapper for this specific exception type? This would be the standard way to do it.

**Comment by franktominc** [comment]
If I define an ExceptionMapper, it will maps everytime the exception is thrown inside the container, right? The problem with it is the exception can be thrown outside a request context. My solution was to define another message body reader wrapping InvalidFormatException into a custom exception and writing a Mapper for it.
