### ISSUE TITLE
Jersey REST POST call throwing 404.

### ISSUE THREAD

**Issue by vishwa141** [jersey/jersey#3788]
My front end component triggers a POST call as : api/certificate/summaries, but in JBoss access.log i could see as below

 - - [21/Mar/2018:13:41:01 -0400] POST /api/certificate/error?version=1&client_id=1005 HTTP/1.1 404 68 %{Referer}i %{User-Agent}i - -

For some reason, its changing to /error since it could not find api/certificate/summaries.

can you please help me here.

**Comment by vishwa141** [comment]
But in reality, i have my resource class which this end point : api/certificate/summaries

**Comment by chkal** [comment]
Are you really using Jersey? JBoss ships with RESTEasy by default. However, you should share more details about you setup and configuration. Without that nobody will be able to help.
